.cargo_lint_template: &cargo_lint
  stage: lint
  script:
    - cargo clippy

.cargo_test_template: &cargo_test
  stage: test
  script:
    - cargo test --all --verbose

stages:
  - lint
  - test
  - deploy

cargo:stable:
  image: rustdocker/rust:stable
  <<: *cargo_test

cargo:beta:
  image: rustdocker/rust:beta
  <<: *cargo_test

cargo:nightly:
  image: rustdocker/rust:nightly
  <<: *cargo_test

cargo:clippy:
  image: rustdocker/rustfmt_clippy:nightly
  <<: *cargo_lint

.pages:
  image: rustdocker/rust:stable
  stage: deploy
  only:
    - master
  script:
    - cargo doc
    - rm -rf public
    - mkdir public
    - cp -R target/doc/* public
  artifacts:
    paths:
    - public
